some updates

diff --git a/general/bin/run-oas b/general/bin/run-oas
--- a/general/bin/run-oas
+++ b/general/bin/run-oas
@@ -1,16 +1,16 @@
 #!/bin/bash
 
 if [ "$#" -ne 2 ]; then
-    echo "Usage: run-oas <full-swagger-path.yaml> <port_number>"
-    exit 1
+  echo "Usage: run-oas <full-swagger-path.yaml> <port_number>"
+  exit 1
 fi
 
 SWAGGER_PATH="$1"
 PORT="$2"
 
 if [ ! -f "$SWAGGER_PATH" ]; then
-    echo "Error: File '$SWAGGER_PATH' not found"
-    exit 1
+  echo "Error: File '$SWAGGER_PATH' not found"
+  exit 1
 fi
 
 SWAGGER_DIR=$(dirname "$SWAGGER_PATH")
